services:
  - type: web
    name: fbo-supply-manager
    env: python
    plan: starter
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: OZON_CLIENT_ID
        sync: false
      - key: OZON_API_KEY
        sync: false
      - key: PORT
        value: 8080
